### ISSUE TITLE
Getting this weird permissions error when using wintun and wireguard go

### ISSUE THREAD

**Issue by 0xdcarns** [WireGuard/wgctrl-go#108]
open \.\pipe\ProtectedPrefix\Administrators\WireGuard\<config name>: This security ID may not be assigned as the owner of this object.

Has anyone else run into this/is there some sort of security policy change to fix it or something in code to fix it?
Does this have to run in a Windows Service potentially?

Steps:
> install wintun.dll
> go build
> run as standalone Win32 binary (.exe) as admin
> Create Tunnel with tun.CreateTun(iface, mtu)
> Create Device with device.NewDevice(...)
> device.Up()
> ipc.UAPIListen(iface) -> fails here

Thanks in advance

**Comment by dosgo** [comment]
So how did you solve this?
