### ISSUE TITLE
Drop staticcheck (honnef.co/go/tools) from go.mod require list

### ISSUE THREAD

**Issue by stv0g** [WireGuard/wgctrl-go#118]
I realized that adding wgctrl as a dependency to my go package pulls in `honnef.co/go/tools` and as transitive dependency.

From my understanding this package is only used to pin a specific `staticcheck` version.

I find it quite unconventional to use the `go.mod` file for this purpose.
At least I haven't seen in any other go package so far.

Can we remove this dependency alongside the `tools.go` file?

**Comment by mdlayher** [comment]
Yep, this is something I had tried out briefly but have been removing from other projects. Will do.

**Comment by stv0g** [comment]
Thanks 👍
