### ISSUE TITLE
Strict netlink option breaks CentOS 7

### ISSUE THREAD

**Issue by jameshartig** [WireGuard/wgctrl-go#119]
On CentOS 7 (kernel 3.10.0-1160.36.2.el7.x86_64) when you call `wgctrl.New()` with fde48d68ee68e3f7af735747d6b97ecb713d924a it returns `setsockopt: protocol not available`. Reverting to the commit before 09ae5327f36693c7f2e252d106245a59395175fb fixes it. If the preference is to enable strict, when available, then maybe it should check for that error and revert back to non-strict if that error is detected?

**Comment by mdlayher** [comment]
Fixed by https://github.com/WireGuard/wgctrl-go/commit/a1499c3d71f131e4a257c6f5a7e3574ae01f7995.
