### ISSUE TITLE
missing go118/netip when building?

### ISSUE THREAD

**Issue by fkooman** [WireGuard/wgctrl-go#122]
When trying to build a project depending on this library, I occasionally get: 

```
go: golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20220330030906-9490840b0b01 requires
	golang.zx2c4.com/wireguard@v0.0.0-20220202223031-3b95c81cc178 requires
	golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found
```

**Comment by mdlayher** [comment]
I was able to build both before and after updating dependencies, so not sure about that one. I've updated everything, so try pulling latest in your project.

**Comment by fkooman** [comment]
> I was able to build both before and after updating dependencies, so not sure about that one. I've updated everything, so try pulling latest in your project.

That was probably because you had that dependency in your cache?

I was able to build it now by fiddling with `go.mod` and `go.sum` (I have no idea how these work). Seems `go118/netip` is no longer a dependency now so it works. Thanks!
