### ISSUE TITLE
Question: Configuring for client

### ISSUE THREAD

**Issue by acheong08** [WireGuard/wgctrl-go#125]
Is it possible to use wgctrl to configure the interface to be a peer? I only see options to configure the device as a server. I apologize for my ignorance.

**Comment by DasSkelett** [comment]
There is no client/server concept in WireGuard. To the protocol, they are all equal peers.
The only difference comes from how you configure AllowedIPs and whether or not you set an Endpoint for a peer. If an Endpoint is set, it will automatically try to connect to the peer, if not it has to wait and listen for incoming handshakes (after which it will save the incoming address and port as (new) Endpoint value).

So you can use this for client configuration without problems. What options are you missing?

**Comment by acheong08** [comment]
I see that ConfigureDevice takes wgtypes.Config which has only 
```
type Config struct {
	PrivateKey *Key

	ListenPort *int

	FirewallMark *int

	ReplacePeers bool

	Peers []PeerConfig
}
```
How do I configure endpoint, address, and PresharedKey?

**Comment by acheong08** [comment]
Is there an easy way to read the configuration from a file and parse it as the Config struct?

**Comment by DasSkelett** [comment]
> How do I configure endpoint, address, and PresharedKey?

https://github.com/WireGuard/wgctrl-go/blob/3d4a969bb56bb6931f6661af606bc9c4195b4249/wgtypes/types.go#L154-L202

**Comment by acheong08** [comment]
Thank you. I was confused into thinking it was for when a peer connects to a server as in the case of a traditional VPN.
