### ISSUE TITLE
Missing DNS?

### ISSUE THREAD

**Issue by GoodiesHQ** [WireGuard/wgctrl-go#127]
There is no member entry for DNS in the `Config` type in the `wgtypes` module and consequently no way of dealing with nameservers.

**PLEASE** note that the DNS field can contain something other than IP addresses, so a type of `[]net.IP` is not desirable. It can also contain search domains which is very important.

**Comment by mdlayher** [comment]
DNS configuration is handled by your operating system (similar to IP address assignment) and thus out of scope for wgctrl-go. Apologies, closing.

**Comment by GoodiesHQ** [comment]
I'm sorry, I'm not sure what you mean. There is a field in the INI configuration of WireGuard called "DNS" which contains two types of values:
- DNS servers that should be used by your OS over the tunnel
- Search domains that should be utilized when 

This is pertaining to the structure that defines the client configuration.

```
[Interface]
PrivateKey = ABCDEFGHIKLMNOPQRSTUVWXYZ=
Address = 10.255.255.4/24
DNS = 192.168.1.250, 1.1.1.1, internal.home.local
```

![image](https://user-images.githubusercontent.com/4576046/196231174-6919fc6a-d4ea-433e-8c60-0993cf656adc.png)

**Comment by mdlayher** [comment]
wg-quick handles IP and DNS assignment in a special way per operating system. They are not configured at all via the interfaces that wgctrl-go provides, and you'd have to implement them separately for each operating system you want your program to work with.
