### ISSUE TITLE
additional hardening on named pipes

### ISSUE THREAD

**Issue by zx2c4** [WireGuard/wgctrl-go#68]
You may want to add an additional hardening measure that winpipe has: https://git.zx2c4.com/wireguard-windows/commit/?id=66adec983e9943cf99886e37fcca9b758cb5938d

**Comment by mdlayher** [comment]
Yep, good idea! Done in https://github.com/WireGuard/wgctrl-go/commit/599d41c32142c0c277590bdfa680795b2b5582a5.
