### ISSUE TITLE
Expose the Client interface

### ISSUE THREAD

**Issue by fastcat** [WireGuard/wgctrl-go#80]
I'm working on an [app](https://github.com/fastcat/wirelink) that uses this library, and for writing my tests it would be very nice to generate a mock for the `Client`.  However, what's exposed/exported from this library is only a concrete wrapper type which implements that interface, but not the interface itself.

Obviously I can copy-paste that interface definition, but being able to directly use the upstream interface avoids some risks down the road.

**Comment by mdlayher** [comment]
Sorry, I'm not really interested in exposing that interface as I consider it to be an implementation detail. In addition, the API is not stable at this time.

I encourage making a small interface in your own code to stub out only the methods you're actually using.
