### ISSUE TITLE
internal/wguser: cannot find tunnels from Mac App Store client

### ISSUE THREAD

**Issue by joneskoo** [WireGuard/wgctrl-go#83]
For some reason wgctrl does not seem to find the tunnels from WireGuard installed from Mac app store on Mac (Catalina).

I tried with this test code:

https://play.golang.org/p/v3nJDCYi8_z

I was expecting it to return devices like on Linux or an error if this is not supported on Mac. Is it possible to support the App Store client or does it not have a standard control socket?

**Comment by mdlayher** [comment]
Apologies for the delay but I don't use a Mac and have no way of troubleshooting this on my own.

If you could find the expected path of the userspace device socket and patch https://github.com/WireGuard/wgctrl-go/blob/1fdaec2702d04e6c38d0130cff92cf499bc20908/internal/wguser/conn_unix.go#L17-L24 to add it to the list, I would expect this to work.

**Comment by joneskoo** [comment]
I tried to look from the WireGuard processes (network extension and UI frontend) but nothing looks like a socket. Didn't find any from filesystem either.

Based on Googling, I don't find anything relevant either.

I give up, I guess there's no Unix socket for WireGuard control on Mac.
