### ISSUE TITLE
how to modfiy the etc/wireguard/wg0.conf[question]

### ISSUE THREAD

**Issue by hujianglong** [WireGuard/wgctrl-go#94]
I want to add / delete peers through wgctrl, and then reflect the relevant changes in conf. next time you start WG again, it will take effect. I don't know how to operate?

**Comment by mdlayher** [comment]
wg-quick and config file operations are outside the scope of this library. You'd have to pull the configuration from the kernel and update the wg-quick configuration file on your own.
