### ISSUE TITLE
Deleting 400 keys takes 10 seconds

### ISSUE THREAD

**Issue by g00nix** [WireGuard/wgctrl-go#95]
Here is the code I use to delete keys:
```go
	peers := []wgtypes.PeerConfig{}
	peers = append(peers, wgtypes.PeerConfig{
		PublicKey: p.PublicKey,
		Remove:    true,
	})
	newConfig := wgtypes.Config{
		ReplacePeers: false,
		Peers:        peers,
	}
	err := c.ConfigureDevice(wgI.Name(), newConfig)
```
I've been running some unit tests and I saw that deletion takes more time than expected. I can add 1000 keys in 1 second, however deleting 400 keys takes 10 seconds and deleting 1000 keys takes 30 seconds.

Is this behavior normal? Can the deletion time be reduced?

**Comment by mdlayher** [comment]
This library doesn't have to do much work to issue a command to the kernel, so if deleting keys is slow, I would contact the mailing list to see if there are known limitations or areas for improvement in this regard. Closing.
