### ISSUE TITLE
Unable to open peer after adding it via wgctl on MacOS

### ISSUE THREAD

**Issue by bilaltahirx** [WireGuard/wgctrl-go#97]
I am unable to access added peer with address using below code on MacOS.
This code works well on both Windows and Linux but on MacOS Added peers dont open.
Is there something else i have to do ?

`	
	

		conf := wgtypes.Config{
			ReplacePeers: true,
			Peers:        peers,
		}

		x,_ := client.Devices()

		a	:= client.ConfigureDevice(x[0].Name, conf)

Using wg-quick route for peer similar to stated below is added automatically
`101.0.0.8/32       utun1              USc             1        0   utun1`
But using wgctl-go route is not added .
Any work around or solution for this on MacOs ??

**Comment by d1ss0nanz** [comment]
wgctrl is working on the level of wg.

wg-quick is a shell script, that does more than wg. If you require such additional functionality, you have to implement it yourself.

**Comment by mdlayher** [comment]
See above, closing.
