### ISSUE TITLE
Unable to download (linux 5.10.11-200.fc33.x86_64)

### ISSUE THREAD

**Issue by ricrug** [WireGuard/wgctrl-go#99]
I'm sure I'm doing something wrong but... it keeps giving me this error

`$ go get -v golang.zx2c4.com/wireguard/wgctrl
get "golang.zx2c4.com/wireguard": found meta tag get.metaImport{Prefix:"golang.zx2c4.com/wireguard", VCS:"git", RepoRoot:"https://git.zx2c4.com/wireguard-go"} at //golang.zx2c4.com/wireguard?go-get=1
go: golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20200205215550-e35592f146e4 requires
	golang.zx2c4.com/wireguard@v0.0.20200121: reading golang.zx2c4.com/wireguard/go.mod at revision v0.0.20200121: unknown revision v0.0.20200121`

**Comment by botto** [comment]
I'm encountering exactly the same problem

**Comment by ricrug** [comment]
I think there are problems with the tag references...

**Comment by ricrug** [comment]
Problem solved! A round of applause for me!
```export GOPROXY=https://proxy.golang.org,direct```
```export GOSUMDB=sum.golang.org```

than `go mod download` will work!
I hope it works for everyone and that I have been helpful!
